version: "3.8"
services:
  postgres_db:
    image: postgres:14.1-alpine
    container_name: bestcoloris_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - "5432:5432"
    volumes:
      - bestcoloris-db:/var/lib/postgresql/data

volumes:
  bestcoloris-db:
